# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Printsoc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Printsoc
  pod 'NMSSH', '~> 2.2.8'

  target 'PrintsocTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Printsoc-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Printsoc-tvOS

  target 'Printsoc-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
